### ISSUE TITLE
<pentry> tags within a group must be distinguished by size or type

### ISSUE THREAD

**Issue by dvolvox** [yath/ghidra-xtensa#14]
Hi,

I'm trying to load a app partition from a ESP32 into Ghidra by using teh xtensa processor. But I get the following exception:

```
Exception reading Xtensa:LE:32:default/default(xtensa.cspec): <pentry> tags within a group must be distinguished by size or type
ghidra.program.model.lang.CompilerSpecNotFoundException: Exception reading Xtensa:LE:32:default/default(xtensa.cspec): <pentry> tags within a group must be distinguished by size or type
	at ghidra.program.model.lang.BasicCompilerSpec.<init>(BasicCompilerSpec.java:157)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.getCompilerSpecByID(SleighLanguage.java:1143)
	at ghidra.app.util.opinion.BinaryLoader.loadProgram(BinaryLoader.java:278)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:113)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: ghidra.xml.XmlParseException: <pentry> tags within a group must be distinguished by size or type
	at ghidra.program.model.lang.ParamEntry.orderWithinGroup(ParamEntry.java:617)
	at ghidra.program.model.lang.ParamListStandardOut.restoreXml(ParamListStandardOut.java:82)
	at ghidra.program.model.lang.PrototypeModel.restoreXml(PrototypeModel.java:559)
	at ghidra.program.model.lang.BasicCompilerSpec.addPrototypeModel(BasicCompilerSpec.java:1048)
	at ghidra.program.model.lang.BasicCompilerSpec.restoreXml(BasicCompilerSpec.java:654)
	at ghidra.program.model.lang.BasicCompilerSpec.initialize(BasicCompilerSpec.java:249)
	at ghidra.program.model.lang.BasicCompilerSpec.<init>(BasicCompilerSpec.java:135)
	... 11 more

---------------------------------------------------
Build Date: 2022-Jul-26 1543 EDT
Ghidra Version: 10.1.5
Java Home: /usr/lib/jvm/java-17-openjdk-amd64
JVM Version: Debian 17.0.9
OS: Linux 6.0.0-kali6-amd64 amd64
```

Can you please help me if this is related to the plugin or the extraction?

Thank you.

**Comment by wojtess** [comment]
same, did you resolve it?
