### ISSUE TITLE
GHidra Version

### ISSUE THREAD

**Issue by plrosa** [yath/ghidra-xtensa#5]
When i try to install this plugin I get

[Fatal Error] generic.log4j.xml:12:50: An include with href 'log4j-appender-console.xml'failed, and no fallback element was found.
2020-12-22 12:00:36,585 main ERROR Error parsing jar:file:/home/plrosa/Téléchargements/ghidra_9.1.2_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml org.xml.sax.SAXParseException; systemId: jar:file:/home/plrosa/Téléchargements/ghidra_9.1.2_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml; lineNumber: 12; columnNumber: 50; An include with href 'log4j-appender-console.xml'failed, and no fallback element was found.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at org.apache.logging.log4j.core.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:95)
	at org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:46)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:244)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:443)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:265)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:613)
	at org.apache.logging.log4j.core.LoggerContext.setConfigLocation(LoggerContext.java:603)
	at ghidra.framework.LoggingInitialization.initializeLoggingSystem(LoggingInitialization.java:49)
	at ghidra.framework.Application.initializeLogging(Application.java:180)
	at ghidra.framework.Application.initializeLogging(Application.java:146)
	at ghidra.framework.Application.initialize(Application.java:94)
	at ghidra.framework.Application.initializeApplication(Application.java:114)
	at ghidra.pcodeCPort.slgh_compile.SleighCompileLauncher.launch(SleighCompileLauncher.java:72)
	at ghidra.GhidraLauncher.main(GhidraLauncher.java:79)

**Comment by yodatak** [comment]
Its because the log4j-appender-console.xml use by default the part of your folder that contain  é "Téléchargements" so move it to /opt/ or /home/plrosa//ghidra_9.1.2_PUBLIC/ and it works for you !
